### ISSUE TITLE
Qdap broken.

### ISSUE THREAD

**Issue by pulkitnandan** [trinker/qdap#214]
I have a shiny project and I don't how to fix this error which is faced by most of the people on windows. I have tried around 16 combinations viz. 64/32 - bits of java and R == 4 Combinations, & 4 for path of environment variable JAVA_HOME.

Here goes the error.

Loading required package: NLP
Loading required package: RColorBrewer
Loading required package: qdapDictionaries
Loading required package: qdapRegex

Attaching package: ‘qdapRegex’

The following object is masked from ‘package:shiny’:

validate
Loading required package: qdapTools
Error : .onLoad failed in loadNamespace() for 'rJava', details:
call: inDL(x, as.logical(local), as.logical(now), ...)
error: unable to load shared object 'C:/Users/Rohit/Documents/R/win-library/3.2/rJava/libs/x64/rJava.dll':
LoadLibrary failure: The specified module could not be found.

Error: package or namespace load failed for ‘qdap’

**Comment by jrosen48** [comment]
Not sure if this is related, but I get the following message when I try to install qdap:

'You need to install the legacy Java SE 6 runtime'

**Comment by trinker** [comment]
You have labeled this as qdap is broken but the error tag shows that it can't install rJava.  Because you haven't got past this point you never install qdap.  This is obviously a java issue.  It sounds like you've tried a number of things.  You say that most people on windows face this problem but I am primarily a Windows user myself.  If my version of R and java version are compatible then qdap never has an issue installing.

The key here is to not focus on qdap but rJava.  Why is it unable to install rJava?

I'd search for:

> Error : .onLoad failed in loadNamespace() for 'rJava', details:
> call: inDL(x, as.logical(local), as.logical(now), ...)

This seems related: http://stackoverflow.com/questions/7019912/using-the-rjava-package-on-win7-64-bit-with-r

**Comment by trinker** [comment]
As there was no response I'm closing for now.  If this did not help feel free to reopen.
