### ISSUE TITLE
wrong reference for Polarity Score?

### ISSUE THREAD

**Issue by randomgambit** [trinker/qdap#238]
Hello,

Thanks for this amazing package. I am looking at the polarity score https://trinker.github.io/qdap/polarity.html and you say:

> The polarity score is dependent upon the polarity dictionary used. This function defaults to the word polarity dictionary used by Hu, M., & Liu, B. (2004),

However, in the reference you mention https://www.aaai.org/Papers/AAAI/2004/AAAI04-119.pdf which does not use a dictionary at all. Is this a typo? Am I missing something?

Thanks!

**Comment by trinker** [comment]
No I referenced it because it greatly influenced my thinking in creating this function...it's important to attribute and acknowledge those that influence your thinking.  References are not only for some sort of facimile...if that were the case one could never debate with those with oposing methods let alone acknowledge parts we admire and repurpose as did with the polarity function.

**Comment by randomgambit** [comment]
yes I understand but here you specifically say  This function defaults to the word polarity dictionary **used by** Hu, M., & Liu, B. (2004), thus making people believe you use something that has been developed in a research paper. if the polarity dictionary is yours, you should perhaps say that you built on Hu and Liu, but you came up with your own dictionary. That would be clearer I think

**Comment by trinker** [comment]
Gotcha.  I didn't connect yoir mention of the references to your first point about the dictionary.  I thought it was a complaimt about referencing a paper that doesn't utiloze the technique used in polarity.  My apologies.

There is indeed a missing reference.  "Mining and summarizing customer reviews." http://www.cs.uic.edu/~liub/publications/kdd04-revSummary.pdf. 

good catch. Could you add this refence and do a pull request please?
